spring:
  profiles:
    active: peer1
debug: true

---
spring:
  profiles: product
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1.eureka:11003/eureka/,http://peer2.eureka:11003/eureka/,http://peer3.eureka:11003/eureka/