spring:
  profiles:
    active: 
    - peer1
    - ${project.environment}

---
spring:
  profiles: test

debug: true

---
spring:
  profiles: product

debug: false

eureka:
  client:
    service-url:
      defaultZone: http://peer1.eureka:11003/eureka/,http://peer2.eureka:11003/eureka/,http://peer3.eureka:11003/eureka/