server:
  port: 8888
  undertow:
      io-threads: 2
      worker-threads: 20
      buffer-size: 1024

spring:
  ### 项目基本信息
  application:
    name: "${server_name}"
    output:
        ansi:
          enabled: always
  profiles:
    active: ${project.environment}

  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true

  output:
    ansi:
      enabled: always

management:
  info.git.mode: full
  security:
    enabled: false
  context-path: /_monitor

---
spring:
  profiles: dev

  cloud:
      config:
        server:
          git:
            uri: https://github.com/MengyeGao/config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://123.103.86.52:11003/eureka/

---
spring:
  profiles: test

  cloud:
      config:
        server:
          git:
            uri: git@192.168.100.21:interview-cool/config-files.git
            ignoreLocalSshSettings: true
            private-key: |
                          -----BEGIN RSA PRIVATE KEY-----
                          MIIEoAIBAAKCAQEArvzJ+QQ/w/Z1IYpM3EvBwCbPTgfydGYD3K30uGu+5E/N+y6w
                          FJCJjjHGM+5A2SnWZH5dShIQV/Nb+ztX/yjEn5KwqKk0/NSh2o41qviPA0ofO816
                          lyYkxdvaBLwshQm4vKbQGH8RWCvCTLH5LVfiiZziDgVVRRULz5rfwcFvKiUS0xNh
                          TsPGy9qGbco2werrAOvLQmsptFMQCMyw34Op8izkuOlmvtZtNsyXtWFV+b9YyZtN
                          uHPYv0wM9gpIk1DZBdXmtUBiAYM2jgJ14MzO1TFK2OQCORBwkLa4btAiro0EZFz6
                          qyJhtrF5tSa7AkHF0SFC6rNlPfYJfeaRMqzHPQIBIwKCAQB3/cxS+5lwbnw0QZPK
                          QpN8cmJEIrTiGhFG3a8fX9NaumFbyD45/LYYXKUq7IQ9JAC58D/4RuaitYDmyZtt
                          I0T/tQtsVsU/p79xS5KD3aPk/6BjhZXj/OYEBHg9wtyy/1oa9gsJe7QfM/Lywy6F
                          fheu0foYPivXmWcvRaC/YBG2fq7DpYHLXlBvMtmtw6p4qV9Wmlq3CnDNXWv34bz0
                          4D47DPQwkXS5Rcgbosf1NJvI7rXFuo2AtjTwEnzPaUUyhbdOwgFKEWnmwerlDUhX
                          kGn13IQ+/Pv15mNixc9io086J9veN1cbsjgvadBtr90qWaBSrGfo6u8vpc7fKKqS
                          vxSLAoGBAOkvTYHENx+uGxw7qMWq/GsRm/4AJ9uXsoS7xXC1NIuBaeetPWIA5OfJ
                          q2ByLSjy30lP4SgUEDKE52qgJHp/nxRGlOhA4kbq+CgYDTaH4RemovcDorEPP/U4
                          /1JLvX/jmDPZtNU9n6XiUmLqyLi7c603yWaFfzb2FbhQjXTpNm8JAoGBAMAbydeX
                          TccmP+y/ZBh8TNTmWV5MqWmbzaMuM2Hv3W5apW5E1+UvwRbvfn5S8h8sg/EOtMHz
                          We5cSaxSFvPUrsQXELyTBLX7Wu09QeCD48dSrL2kEGG4iypnrEJd5Hnreq/ml3EP
                          yX855MbVEt++YLl2HG+G3ZF3uS4n6HjeH6+VAoGAcULcgNulvu4qbMyFLM9kqQiN
                          mKD9aqjEbFs0A4s2x2q+aTbjTNvc5Zx3z8JttM286RgriH7GCejILHmrUXEwAoiu
                          ufOhGyGru7PpKR1tVKFlGOSCOL5Dov5tYnyPPh4WuhlJNF/CkmadC3laLddkEk5L
                          4VbIwuyONPPs76R5hmMCgYBHWsdQE6CLzGDi6ACbYV5dtKTZ4fXII+1LPQvFSnbR
                          N5yICvEanLVu6z2concwJnomVetd+01J58OXxrgRbEDpv2yd0DTzItihQqNwpgQl
                          dnqs1om95XWEx2veIt/Vg1l0iNkp/oyrmSkWpunA0a7lzMi7tcAC1LJ+2599WdFB
                          NwKBgCn/ZK3BiHly6/aIolgRwjgiUcgaAVEXRh8OgcrVsLueBLU6aVV39k9S9ORJ
                          8i/quVtb2v5DUTyB3LAtBLo6tSWIs41K33OEoTNOk/GixLHkApjHUTFVMlkKRbay
                          Rsfc2BnLdr+j5c0Dd2BtagJvBhiwAn/UBDywO6agtsMQZEdy
                          -----END RSA PRIVATE KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.22:11003/eureka/