server:
  port: 11005
  undertow:
      io-threads: 2
      worker-threads: 20
      buffer-size: 1024

#zuul:
#  routes:
#    cloud-u:
#      path: /u/**   #路由路径
#      url: http://123.103.86.52:11010/   #指定URL地址
#      serviceId:user-service    //推荐下面这个


spring:
  ### 项目基本信息
  application:
    name: "${server_name}"
    profiles:
      active: ${project.environment}
    output:
      ansi:
        enabled: always
  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true

  output:
    ansi:
      enabled: always


---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://123.103.86.52:11003/ #配置Eureka Server
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://123.103.86.52:11003/ #配置Eureka Server