server:
  port: 11005
  undertow:
      io-threads: 2
      worker-threads: 20
      buffer-size: 1024
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11003/eureka #配置Eureka Server

#配置示例
zuul:
  routes:
    api-search-server:
      path: /s/**
      serviceId: search-server
    api-user-server:
      path: /user/**
      serviceId: user-server
    api-tiku-server:
      path: /tk/**
      serviceId: ic-tiku-server
  retryable: true  #路由重试
ribbon:
#  ribbon重试超时时间
  ConnectTimeout: 250
#  建立连接后的超时时间
  ReadTimeout: 1000
#  对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
#  切换实例的重试次数
  MaxAutoRetriesNextServer: 1
#  对当前实例的重试次数
  MaxAutoRetries: 1
  eureka:
      enable: true
spring:
  ### 项目基本信息
  application:
    name: "${server_name}"
    profiles:
      active: "${project.environment}"
  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  mvc:
    throw-exception-if-no-handler-found: true

  output:
    ansi:
      enabled: always
  #hystrix dashboard的信息收集频率
  cloud:
    hypermedia:
      refresh:
        fixed-delay: 5000
management:
  info.git.mode: full
  security:
    enabled: false
  context-path: /_monitor
